@echo off
mkdir Release
mkdir Release\CD
mkdir Release\CD\XLDLIBS
mkdir Release\CD\XLDLIBS\ENGLISH
mkdir Release\CD\XLDLIBS\FRENCH
mkdir Release\CD\XLDLIBS\GERMAN
mkdir Release\CD\XLDLIBS\INITIAL
mkdir Release\XLDLIBS
mkdir Release\XLDLIBS\INITIAL

copy /Y Albion\CD\XLDLIBS\3DOBJEC1.XLD         Release\CD\XLDLIBS\3DOBJEC1.XLD
copy /Y Albion\CD\XLDLIBS\3DOBJEC2.XLD         Release\CD\XLDLIBS\3DOBJEC2.XLD
copy /Y Albion\CD\XLDLIBS\3DOVERL0.XLD         Release\CD\XLDLIBS\3DOVERL0.XLD
copy /Y Albion\CD\XLDLIBS\3DOVERL1.XLD         Release\CD\XLDLIBS\3DOVERL1.XLD
copy /Y Albion\CD\XLDLIBS\EVNTSET0.XLD         Release\CD\XLDLIBS\EVNTSET0.XLD
copy /Y Albion\CD\XLDLIBS\EVNTSET1.XLD         Release\CD\XLDLIBS\EVNTSET1.XLD
copy /Y Albion\CD\XLDLIBS\EVNTSET2.XLD         Release\CD\XLDLIBS\EVNTSET2.XLD
copy /Y Albion\CD\XLDLIBS\EVNTSET3.XLD         Release\CD\XLDLIBS\EVNTSET3.XLD
copy /Y Albion\CD\XLDLIBS\FBODPIX0.XLD         Release\CD\XLDLIBS\FBODPIX0.XLD
copy /Y Albion\CD\XLDLIBS\LABDATA0.XLD         Release\CD\XLDLIBS\LABDATA0.XLD
copy /Y Albion\CD\XLDLIBS\LABDATA1.XLD         Release\CD\XLDLIBS\LABDATA1.XLD
copy /Y Albion\CD\XLDLIBS\LABDATA2.XLD         Release\CD\XLDLIBS\LABDATA2.XLD
copy /Y Albion\CD\XLDLIBS\MAPDATA1.XLD         Release\CD\XLDLIBS\MAPDATA1.XLD
copy /Y Albion\CD\XLDLIBS\MAPDATA2.XLD         Release\CD\XLDLIBS\MAPDATA2.XLD
copy /Y Albion\CD\XLDLIBS\MAPDATA3.XLD         Release\CD\XLDLIBS\MAPDATA3.XLD
copy /Y Albion\CD\XLDLIBS\MONCHAR0.XLD         Release\CD\XLDLIBS\MONCHAR0.XLD
copy /Y Albion\CD\XLDLIBS\NPCGR0.XLD           Release\CD\XLDLIBS\NPCGR0.XLD
copy /Y Albion\CD\XLDLIBS\NPCKL0.XLD           Release\CD\XLDLIBS\NPCKL0.XLD
copy /Y Albion\CD\XLDLIBS\PARTGR0.XLD          Release\CD\XLDLIBS\PARTGR0.XLD
copy /Y Albion\CD\XLDLIBS\PARTKL0.XLD          Release\CD\XLDLIBS\PARTKL0.XLD
copy /Y Albion\CD\XLDLIBS\SMLPORT0.XLD         Release\CD\XLDLIBS\SMLPORT0.XLD
copy /Y Albion\CD\XLDLIBS\SMLPORT1.XLD         Release\CD\XLDLIBS\SMLPORT1.XLD
copy /Y Albion\CD\XLDLIBS\TACTICO0.XLD         Release\CD\XLDLIBS\TACTICO0.XLD
copy /Y Albion\CD\XLDLIBS\ENGLISH\EVNTTXT0.XLD Release\CD\XLDLIBS\ENGLISH\EVNTTXT0.XLD
copy /Y Albion\CD\XLDLIBS\ENGLISH\EVNTTXT1.XLD Release\CD\XLDLIBS\ENGLISH\EVNTTXT1.XLD
copy /Y Albion\CD\XLDLIBS\ENGLISH\EVNTTXT2.XLD Release\CD\XLDLIBS\ENGLISH\EVNTTXT2.XLD
copy /Y Albion\CD\XLDLIBS\ENGLISH\EVNTTXT3.XLD Release\CD\XLDLIBS\ENGLISH\EVNTTXT3.XLD
copy /Y Albion\CD\XLDLIBS\ENGLISH\EVNTTXT9.XLD Release\CD\XLDLIBS\ENGLISH\EVNTTXT9.XLD
copy /Y Albion\CD\XLDLIBS\ENGLISH\MAPTEXT1.XLD Release\CD\XLDLIBS\ENGLISH\MAPTEXT1.XLD
copy /Y Albion\CD\XLDLIBS\ENGLISH\MAPTEXT2.XLD Release\CD\XLDLIBS\ENGLISH\MAPTEXT2.XLD
copy /Y Albion\CD\XLDLIBS\ENGLISH\MAPTEXT3.XLD Release\CD\XLDLIBS\ENGLISH\MAPTEXT3.XLD
copy /Y Albion\CD\XLDLIBS\ENGLISH\SYSTEXTS     Release\CD\XLDLIBS\ENGLISH\SYSTEXTS
copy /Y Albion\CD\XLDLIBS\ENGLISH\WORDLIS0.XLD Release\CD\XLDLIBS\ENGLISH\WORDLIS0.XLD
copy /Y Albion\CD\XLDLIBS\FRENCH\EVNTTXT0.XLD  Release\CD\XLDLIBS\FRENCH\EVNTTXT0.XLD
copy /Y Albion\CD\XLDLIBS\FRENCH\EVNTTXT1.XLD  Release\CD\XLDLIBS\FRENCH\EVNTTXT1.XLD
copy /Y Albion\CD\XLDLIBS\FRENCH\EVNTTXT2.XLD  Release\CD\XLDLIBS\FRENCH\EVNTTXT2.XLD
copy /Y Albion\CD\XLDLIBS\FRENCH\EVNTTXT3.XLD  Release\CD\XLDLIBS\FRENCH\EVNTTXT3.XLD
copy /Y Albion\CD\XLDLIBS\FRENCH\EVNTTXT9.XLD  Release\CD\XLDLIBS\FRENCH\EVNTTXT9.XLD
copy /Y Albion\CD\XLDLIBS\FRENCH\MAPTEXT1.XLD  Release\CD\XLDLIBS\FRENCH\MAPTEXT1.XLD
copy /Y Albion\CD\XLDLIBS\FRENCH\MAPTEXT2.XLD  Release\CD\XLDLIBS\FRENCH\MAPTEXT2.XLD
copy /Y Albion\CD\XLDLIBS\FRENCH\MAPTEXT3.XLD  Release\CD\XLDLIBS\FRENCH\MAPTEXT3.XLD
copy /Y Albion\CD\XLDLIBS\FRENCH\SYSTEXTS      Release\CD\XLDLIBS\FRENCH\SYSTEXTS
copy /Y Albion\CD\XLDLIBS\FRENCH\WORDLIS0.XLD  Release\CD\XLDLIBS\FRENCH\WORDLIS0.XLD
copy /Y Albion\CD\XLDLIBS\GERMAN\EVNTTXT0.XLD  Release\CD\XLDLIBS\GERMAN\EVNTTXT0.XLD
copy /Y Albion\CD\XLDLIBS\GERMAN\EVNTTXT1.XLD  Release\CD\XLDLIBS\GERMAN\EVNTTXT1.XLD
copy /Y Albion\CD\XLDLIBS\GERMAN\EVNTTXT2.XLD  Release\CD\XLDLIBS\GERMAN\EVNTTXT2.XLD
copy /Y Albion\CD\XLDLIBS\GERMAN\EVNTTXT3.XLD  Release\CD\XLDLIBS\GERMAN\EVNTTXT3.XLD
copy /Y Albion\CD\XLDLIBS\GERMAN\EVNTTXT9.XLD  Release\CD\XLDLIBS\GERMAN\EVNTTXT9.XLD
copy /Y Albion\CD\XLDLIBS\GERMAN\MAPTEXT1.XLD  Release\CD\XLDLIBS\GERMAN\MAPTEXT1.XLD
copy /Y Albion\CD\XLDLIBS\GERMAN\MAPTEXT2.XLD  Release\CD\XLDLIBS\GERMAN\MAPTEXT2.XLD
copy /Y Albion\CD\XLDLIBS\GERMAN\MAPTEXT3.XLD  Release\CD\XLDLIBS\GERMAN\MAPTEXT3.XLD
copy /Y Albion\CD\XLDLIBS\GERMAN\SYSTEXTS      Release\CD\XLDLIBS\GERMAN\SYSTEXTS
copy /Y Albion\CD\XLDLIBS\GERMAN\WORDLIS0.XLD  Release\CD\XLDLIBS\GERMAN\WORDLIS0.XLD
copy /Y Albion\CD\XLDLIBS\INITIAL\NPCCHAR0.XLD Release\CD\XLDLIBS\INITIAL\NPCCHAR0.XLD
copy /Y Albion\CD\XLDLIBS\INITIAL\NPCCHAR1.XLD Release\CD\XLDLIBS\INITIAL\NPCCHAR1.XLD
copy /Y Albion\CD\XLDLIBS\INITIAL\NPCCHAR2.XLD Release\CD\XLDLIBS\INITIAL\NPCCHAR2.XLD
copy /Y Albion\CD\XLDLIBS\INITIAL\PRTCHAR0.XLD Release\CD\XLDLIBS\INITIAL\PRTCHAR0.XLD
copy /Y Albion\CD\XLDLIBS\INITIAL\PRTCHAR1.XLD Release\CD\XLDLIBS\INITIAL\PRTCHAR1.XLD
copy /Y Albion\CD\XLDLIBS\INITIAL\PRTCHAR2.XLD Release\CD\XLDLIBS\INITIAL\PRTCHAR2.XLD
copy /Y Albion\XLDLIBS\INITIAL\NPCCHAR0.XLD    Release\XLDLIBS\INITIAL\NPCCHAR0.XLD
copy /Y Albion\XLDLIBS\INITIAL\NPCCHAR1.XLD    Release\XLDLIBS\INITIAL\NPCCHAR1.XLD
copy /Y Albion\XLDLIBS\INITIAL\NPCCHAR2.XLD    Release\XLDLIBS\INITIAL\NPCCHAR2.XLD
copy /Y Albion\XLDLIBS\INITIAL\PRTCHAR0.XLD    Release\XLDLIBS\INITIAL\PRTCHAR0.XLD
copy /Y Albion\XLDLIBS\INITIAL\PRTCHAR1.XLD    Release\XLDLIBS\INITIAL\PRTCHAR1.XLD
copy /Y Albion\XLDLIBS\INITIAL\PRTCHAR2.XLD    Release\XLDLIBS\INITIAL\PRTCHAR2.XLD
